# define the base image
FROM node:alpine

# define paths and copy the files
WORKDIR '/app'
COPY package.json .

# Install the dependencies
RUN npm install

COPY . .


# Define start up command
CMD ["npm", "run", "start"]